# Generated by Django 6.1 on 2026-08-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('sector', models.CharField(max_length=128)),
                ('currency', models.CharField(max_length=8)),
                ('locale', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
