# Generated by Django 6.1 on 2026-08-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('model_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('model_code', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('primitive_diameter', models.FloatField(blank=True, null=True)),
                ('cap_type', models.CharField(blank=True, max_length=128)),
                ('container_type', models.CharField(blank=True, max_length=128)),
                ('nominal_heads', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('industry_segment', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name_plural': 'MachinesModel',
            },
        ),
    ]
