# Generated by Django 6.1 on 2026-08-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_machinemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinemodel',
            options={'verbose_name_plural': 'Machine Models'},
        ),
    ]
