# Generated by Django 6.1 on 2026-08-10 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_machinemodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('plant_location', models.CharField(blank=True, max_length=256)),
                ('configuration_profile', models.TextField(blank=True)),
                ('plc_family', models.CharField(blank=True, choices=[('SIEMENS-SIMATIC-S7', 'Siemens Simatic S7'), ('LINE-PLC-INTEGRATED', 'Line PLC Integrated'), ('HARDWIRED-CONTROL-PANEL', 'Hardwired Control Panel')], max_length=32)),
                ('software_version', models.CharField(blank=True, max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='core.company')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='core.machinemodel')),
            ],
        ),
    ]
