# Generated by Django 6.1 on 2026-08-10 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('alarm_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('alarm_code', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=16)),
                ('alarm_status', models.CharField(choices=[('Open', 'Open'), ('Acknowledged', 'Acknowledged'), ('Resolved', 'Resolved')], max_length=16)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='core.machine')),
            ],
        ),
    ]
