# Generated by Django 6.1 on 2026-08-10 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('ticket_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(choices=[('Remote troubleshooting', 'Remote Troubleshooting'), ('On-site service', 'On-site Service'), ('Spare parts request', 'Spare Parts Request'), ('Scheduled maintenance', 'Scheduled Maintenance'), ('Overhaul', 'Overhaul'), ('Size change assistance', 'Size Change Assistance')], max_length=32)),
                ('ticket_status', models.CharField(choices=[('Open', 'Open'), ('In progress', 'In progress'), ('Waiting for parts', 'Waiting for parts'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], max_length=32)),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=16)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('owner_role', models.CharField(choices=[('Line Operator', 'Line Operator'), ('Maintenance Man', 'Maintenance Man'), ('Plant Maintenance Manager', 'Plant Maintenance Manager'), ('AROL Technical Service', 'AROL Technical Service')], max_length=32)),
                ('alarm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to='core.alarm')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='core.machine')),
            ],
        ),
    ]
