# Generated by Django 6.1 on 2026-08-10 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_maintenanceticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetrySnapshot',
            fields=[
                ('telemetry_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('operational_status', models.CharField(choices=[('Running', 'Running'), ('Alarm', 'Alarm'), ('Idle', 'Idle'), ('Stopped', 'Stopped'), ('Maintenance', 'Maintenance'), ('Size change', 'Size change')], max_length=16)),
                ('production_rate_bph', models.FloatField(blank=True, null=True)),
                ('uptime_percentage', models.FloatField(blank=True, null=True)),
                ('alarm_count', models.IntegerField(default=0)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('energy_kwh', models.FloatField(blank=True, null=True)),
                ('health_note', models.TextField(blank=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_snapshots', to='core.machine')),
            ],
        ),
    ]
