# Generated by Django 6.1 on 2026-08-10 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_telemetrysnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('In production', 'In production'), ('Delivered', 'Delivered'), ('Closed', 'Closed')], max_length=16)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('shipment_status', models.CharField(choices=[('In production', 'In production'), ('Ready for shipment', 'Ready for shipment'), ('Delivered', 'Delivered'), ('Installed', 'Installed')], max_length=20)),
                ('currency', models.CharField(max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('order_line_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('fulfillment_status', models.CharField(choices=[('Manufacturing', 'Manufacturing'), ('Ready for shipment', 'Ready for shipment'), ('Delivered', 'Delivered')], max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quote_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('currency', models.CharField(max_length=8)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.company')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.quote'),
        ),
        migrations.CreateModel(
            name='QuoteRevision',
            fields=[
                ('quote_revision_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('revision_number', models.IntegerField()),
                ('revision_status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Superseded', 'Superseded'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], max_length=16)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('discount_rate', models.FloatField(default=0)),
                ('change_summary', models.TextField(blank=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.quote')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('quote_line_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_lines', to='core.machine')),
                ('quote_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.quoterevision')),
            ],
        ),
    ]
